label buildroot
	kernel /zImage
	devicetree /bcm2835-rpi-b-plus.dtb
#	devicetree /bcm2835-rpi-zero-w.dtb
#	devicetree-overlay /ssd1306.dtbo
	append root=/dev/mmcblk0p2 rootwait console=tty1 console=ttyAMA0,115200

# In Raspberry Pi Zero W, the mini-uart is used for console instead of the PL011:
#	append root=/dev/mmcblk0p2 rootwait console=tty1 console=ttyS1,115200
